### ISSUE TITLE
Sometimes GLaDOS retriggers after speaking

### ISSUE THREAD

**Issue by salleq** [nerdaxic/glados-voice-assistant#15]
This doesn't happen all the time but often enough that I've noticed:
I trigger GLaDOS, say the command, she speaks back and immediately triggers herself.

Right now I'm doing this on a laptop microphone and speakers so it could be that she triggers herself from her previous output, but it's not consistent even when saying the same command.
It's like sometimes it jumps directly from "waiting for trigger" to actually listening to what I have to say, but it fails immediately and I get the "you really need to write better code" error.

**Comment by nerdaxic** [comment]
Same issue here. pocketsphinx is constantly listening and the robot can trigger itself.
This issue should be gone once [wake word detector model](https://github.com/nerdaxic/glados-voice-assistant/discussions/6) is implemented.

**Solution:** Will not fix. Will be fixed with oncoming architechture change.
