### ISSUE TITLE
RuntimeError: espeak not installed on your system

### ISSUE THREAD

**Issue by Vexthecollector** [nerdaxic/glados-voice-assistant#24]
Using Windows
Running Python 3.9.7
I have both the old espeak and espeak NG installed

I tried to install just the tts package itself, I managed to install everything, but it does not seem to find espeak, no matter what I try.
I have set up the environment variables as others have mentioned in their issues https://github.com/nerdaxic/glados-voice-assistant/issues/22 and https://github.com/bootphon/phonemizer/issues/44
(I think I assume corectly I have to set it up with the Windows Environment Variables)

But the result is the same. It fails in line 67 of utils\cleaners.py which then points to phonemizer failing. Specifically espeak\espeak.py (line 45 super().__init__ ) and espeak\base.py (line 35 super().__init__)

I haven't really messed with espeak and phonemizer before, so I am unsure if I am failing something obvious, or if there is an issue with some code. Most likely me failing.

**Comment by eternalliving** [comment]
Yes, you need to set the environment variables within Windows itself, you may need to log out and back in for it to take effect.

I remember trying a lot of things to get it work and sadly I don't remember exactly what did it. I think an older version uses ESPEAK_LIBRARY instead of ESPEAK_PATH... eitherway, here is my current windows environment variables and it is working:
```
PHONEMIZER_ESPEAK_LIBRARY = C:\Program Files\eSpeak NG\libespeak-ng.dll
PHONEMIZER_ESPEAK_PATH = C:\Program Files\eSpeak NG\espeak-ng.exe
```
Let me know if either of those work for you and we'll try to write it into the documentation for future reference.

**Comment by Vexthecollector** [comment]
Seems like the problem was just a restart.

Thanks for the support and the amazing software!

**Comment by apokalipo** [comment]
Hey I'm having the same issue. I tried everything mentioned in this and every other familiar issue, but nothing seems to help. (In PyCharm) The console still gives the error: `RuntimeError: espeak not installed on your system`
